<?php 

// Remplissage des listes pour la recherche

const STATUT =["Cadre", "Employé", "Practicien", "N/A", "Etudiant" ];

const CONTRAT = ["CDI","CDD", "Stage", "Autre"];

const AGENCE = [
"MSA Caisse Centrale",
"MSA Alpes du Nord",
"MSA Mayenne Orne Sarthe",
"MSA Bourgogne",
"MSA Limousin",
"MSA Ile de France",
"MSA Midi Pyrénées Nord",
"MSA Alsace",
"MSA Loire Atlantique Vendée",
"MSA Armorique",
"MSA Auvergne",
"MSA Informatique",
"MSA Berry Touraine",
"MSA Beauce Coeur de Loire",
"MSA Portes de Bretagne",
"MSA Côtes Normandes",
"MSA Haute Normandie",
"MSA Lorraine",
"MSA Alpes Vaucluse",
"MSA Languedoc",
"MSA Maine et Loire",
"MSA Gironde",
"MSA Ardèche Drôme Loire",
"MSA Dordogne Lot et Garonne",
];

const TYPEJOB = [
"Chargé de mission pilotage (F/H)",
"Gestionnaire comptable",
"Délégué(e)/Fondé(e) de pouvoir",
"Agent de développement social local F/H",
"Agent de développement social local F/H",
"Chef de projet MOA Junior - Prestations Familiales (F/H)",
"Chef de projet MOA Confirmé - Prestations Familiales (F/H)",
"Chef de projet SI (F/H)",
"Chargé de mission Processus (F/H)",
"Gestionnaire comptable",
"Délégué(e)/Fondé(e) de pouvoir",
"Chargé de mission pilotage (F/H)",
"Infirmier santé au travail (F/H)",
"EXPERT POA",
"Assistant secrétariat commission médicale nationale (F/H)",
"Technicien back office retraite",
"2 Techniciens PSSP f/h",
"Développeur full stack / Office 365 Online (F/H)",
"Chargé de projet RH - Gestion des compétences (F/H)",
"Juriste droit du travail (F/H)",
"Médecin conseil",
"Téléconseils CAF H/F",
"Candidature stage F/H",
"Comptable (f/h)",
"Gestionnaire de prestations santé (H/F)",
"Conseiller accueil MSA H/F",
"Conseiller accueil MSA H/F",
"1 Rédacteur juridique F/H en CDI",
"Travailleur Social",
"CONSEILLER TECHNIQUE H/F",
"System Architect Engineer (SAE) H/F (82)",
"Data Plateform Engineer Socle Big Data - H/F (93)",
"2 TECHNICIENS CDD PRESTATIONS FAMILIALES",
"1 TECHNICIEN PRESTATIONS FAMILIALES CDD 50%",
"Leader technique Big Data H/F (59)",
"Leader technique Big Data H/F (82)",
"Leader technique Big Data H/F (93)",
"Secrétaire au Service Développement des Territoires",
"Analyste/Développeur COBOL H/F (82)",
"Gestionnaire des moyens généraux",
"Tech Lead Java J2EE H/F (82)",
"Technicien Recouvrement (Orléans) H/F",
"R 05/2022 - Téléconseiller adhérents/clients - Site de Vannes (F/H)",
"R 05/2022 - Téléconseiller adhérents/clients - Site de Bruz (F/H)",
"Infirmier(e) en santé sécurité au travail",
"Opérateurs cotisations",
"administrateur informatique départementale",
"Attaché de presse (F/H)",
"Data Plateform Engineer Socle Big Data - H/F (82)",
"Assistant en protection sociale à la médiation (F/H)",
"Data Plateform Engineer Socle Big Data - H/F (59)",
"AGENT ADMINISTRATIF RETRAITE H/F",
"Comptable H/F",
"Secrétaire au sein du domaine Contrôle médical et dentaire (H/F)",
"Responsable des Travailleurs Sociaux - Tours de préférence",
"Product Manager Santé (F/H)",
"Infirmier(ère) en Contrôle Médical H/F",
"Technicien GEIDE",
"Chef de projet MOA Confirmé Relation de Service (F/H)",
"Chef de projet MOA Confirmé Santé (F/H)",
"Responsable Paie et Administration du Personnel (H/F)",
"Assistant administratif action sociale H/F",
"2 TELECONSEILLERS",
"AC 27/2021 - Correspondant/Conseiller à l'accueil - Monfort s/ Meu (F/H)",
"Tech Lead Java H/F (59)",
"Assistant de service social H/F",
"2 TECHNICIENS RETRAITE",
"Gestionnaire Prestations- Service Retraite",
"Responsable de service comptabilité (F/H)",
"Gestionnaire des biens et des services (H/F)",
"R 24/2021 - Médecin du Travail - SST (Morbihan)",
"VERIFICATEUR COMPTABLE",
"Acheteur H/F",
"Animateur d'équipe plateforme de services H/F",
"Technicien Cotisations Non salariés agricoles - H/F",
"Juriste marchés publics (H/F)",
"Technicien administratif (H/F)",
"Technicien prestations assurance maladie (H/F)",
"Expert Prestations Assurance Maladie (H/F)",
"Analyste Informaticien",
"Juriste Protection Sociale - Simplification et Cotisations des non salariés agricoles (F/H)",
"Juriste protection sociale - Simplification et Cotisations des non salariés agricoles (F/H)",
"Juriste protection sociale - Simplification et Cotisations sur salaire (F/H)",
"Médecin conseil orientation expertise médico sociale",
"gestionnaire achats",
"Conseiller(ère) Social(e) F/H",
"Rédacteur(trice) Juridique F/H",
"EXPERT PAYE PIVOT",
"Correspondant à l'accueil - CDD - 9 mois",
"Comptable en charge du budget (H/F)",
"Infirmier SST H/F",
"Technicien en gestion des droits H/F",
"Technicien prestations familiales H/F",
"Tech Lead Java H/F (82)",
"Technicien Recouvrement de créances H/F",
"Assistante RH - Gestion de la paie",
"Juriste retraite (F/H)",
"Chargé d'étude santé publique",
"Chef de projet MOA – Prévention Sanitaire et sociale (F/H)",
"Responsable du service Santé (F/H)",
"GESTIONNAIRE COMPTABLE",
"Agent administratif Prestations Assurance Maladie (F/H)",
"Assistant administratif Prestations Familiales et de Solidarité (F/H)",
"Gestionnaire Paie H/F (82)",
"Gestionnaire Paie H/F (38)",
"Directeur d'Association - ASEPT (F/H)",
"INFIRMIER / INFIRMIÈRE SECTEUR INTERVENTION SUD DROME",
"INFIRMIER / INFIRMIÈRE secteur intervention Privas et Aubenas",
"Technicien administratif H/F",
"Chargé de développement territorial en Santé ( H / F )",
"Expert Système Microsoft H/F (82)",
"Cadre en Santé Publique ( H / F )",
"Technicien Prestations Santé (F/H)",
"Développeur Java et ODM H/F (82)",
"Infirmier du service du Contrôle Médical (F/H)",
"Technicien back office Invalidité",
"Concepteur Technique Java H/F (59)",
"Concepteur Technique Java H/F (93)",
"Expert Technique Système H/F (82)",
"Manager d\'équipiers H/F (59)",
"Correspondant à l’accueil en CDD France Services Tain L’Hermitage (26) - EXTERNE",
"Agent d\'accueil en Sécurité Sociale (F/H)",
"Chef de projet digital (F/H)",
"Assistant en Ressources Humaines ( H/F)",
"Responsable du Contrôle Externe et du Management des Risques (H/F)",
"Responsable de Service Relation de Service",
"Analyste Expert Applicatif H/F (54)",
"Cadre référent Relation Client",
"Responsable de Service Cotisation et Recouvrement Contentieux",
"Gestionnaire contentieux",
"Chargé d\'études service contentieux",
"Opérateur de prestation santé ratp",
"Assistant de direction (F/H)",
"Responsable Achats-Contrats-Marchés",
"Conseiller Prévention",
"Secrétaire médicale",
"Médecin du travail H/F",
"Conseiller en prévention des risques professionnels H/F",
"Médecin conseil H/F",
"Gestionnaire administratif Santé sécurité au Travail ( H/F)",
"Téléconseiller",
"Médecin Chef Santé au Travail H/F",
"Adjoint au responsable du département de l’accompagnement et du développement social (F/H)",
"Médecin du Travail H/F (2 postes)",
"TECHNICIEN SERVICE AFFAIRES JURIDIQUES (F/H)",
"Conseiller(ère) en Prévention et Sécurité au Travail F/H",
"Responsable département Pilotage, MOS et Poste de l\'Agent (F/H)",
"Chargé d\'accueil France Services Eymoutiers (F/H)",
"Technicien prestations santé (H/F)",
"Agent de Développement Social Local (F/H)",
"REDACTEUR JURIDIQUE",
"CORRESPONDANT ACCUEIL",
"SECRETAIRE SERVICE SANTE AU TRAVAIL",
"Technicien(ne) d\'entretien et de maintenance du bâtiment H/F",
"Chef de projet MOA Confirmé Poste de l\'Agent (F/H)",
"Consultant Organisation / Chargé de projet (F/H)",
"Chef de projet Relation de Service (F/H)",
"Leader Technique H/F (82)",
"Médecins du travail H/F - Départements 36 ou 37 ou 41",
"Expert Système H/F (82)",
"Agile Project Management Office H/F (93)",
"Assistant(e) Fonctionnel(le) H/F (54)",
"Chef de projet MOA Confirmé Pilotage (F/H)",
"Assistant développement ressources humaines formation/recrutement",
"Médecin du Travail (F/H)",
"Animateur de territoire (F/H)",
"Coordonnateur(trice) de l\'offre de services (F/H)",
"Secrétaire général(e) (F/H)",
"Responsable du département Comptabilité Finances H/F",
"Chargé de mission en protection sociale (F/H)",
"Chef de projet MOA Confirmé Comptabilité (F/H)",
"Chef de projet MOA junior - Santé (F/H)",
"Adjoint au Responsable du département MOA Santé (F/H)",
"Chef de projet MOA Junior Poste de l`\'Agent (F/H)",
"Chef de projet MOA Junior Pilotage (F/H)",
"Chef de projet MOA Confirmé Santé - Partenariats (F/H)",
"Coordinateur Pédagogique - Chargé(e) de clientèle pour son pôle formation (F/H)",
"Chef de Projet MOA H/F (93)",
"Médecin Conseil (F/H)",
"Concepteur Développeur JAVA H/F (82)",
"Concepteur Développeur JAVA/J2EE confirmé H/F (82)",
"Stagiaire H/F (82)",
"Juriste (F/H)",
"Operateur / Operatrice en numérisation",
"Technicien / Technicienne en numérisation",
"Gestionnaire paie ( H/F)",
"Technicien paie ( H/F)",
"Acheteur Informatique H/F (82)",
"Architecte Technique H/F (82)",
"Travailleur social spécialisé (F/H)",
"Manager Sourcing H/F (82)",
"1 médecin du travail H/F",
"Concepteur Décisionnel H/F (93)",
"Offre de stage Motion Designer",
"3 Médecins du travail (F/H)",
"Médecin du travail en CDI (H/F)",
"Médecin Conseil H/F"
];

?>